const AUTH_LOADING = "AUTH_LOADING";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAILED = "AUTH_FAILED";
const RESET_AUTH = "RESET_AUTH";
const LOGOUT = "LOGOUT";

export {
    RESET_AUTH,
    AUTH_LOADING,
    AUTH_SUCCESS,
    AUTH_FAILED,
    LOGOUT
}